In [2]:
import numpy as np 

In [ ]:
a = np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [ ]:
b = np.array([[4,5], [6,7]])
b


array([[4, 5],
       [6, 7]])

In [ ]:
fuyad = np.array([1,2,3], "complex")
fuyad

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
d = np.array((1,2,3))
d

array([1, 2, 3])

In [ ]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [ ]:
np.arange(2,16,3)

array([ 2,  5,  8, 11, 14])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(20, dtype="complex")

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

Numpy Zeros()

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros(2, dtype=int)

array([0, 0])

In [ ]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

numpy ones()

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [ ]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

numpy eye()

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.randint(15, size=5)

array([ 7,  8, 11,  9,  2])

In [ ]:
np.random.randn(5,2)

array([[-0.11421215,  1.26403363],
       [ 0.77391732, -1.47102226],
       [-0.20998866, -1.17941571],
       [-2.14758039,  1.65536527],
       [-0.75296217,  2.07716587]])

In [ ]:
np.random.rand(5)

array([0.16869914, 0.89488643, 0.01605952, 0.22572385, 0.28681542])

In [ ]:
np.random.randint(5)

4

In [ ]:
np.random.ranf(10)

array([0.72722472, 0.11983652, 0.21251435, 0.79547666, 0.26545611,
       0.95754467, 0.74960652, 0.38836403, 0.15650727, 0.02984148])

Indexing in numpy array

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a[2]

3

In [ ]:
b = np.array([[1,2,3], [4,5,6]])
b.ndim

2

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b[1][1]

5

In [ ]:
b[0][0]

1

In [ ]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
c.ndim

3

In [ ]:
a[1:3]

array([2, 3])

Slicing in numpy

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
a[4]

5

Advance Indexing

In [ ]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[[1,4,5]]

array([2, 5, 6])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[[2,0],[0,2]]

array([7, 3])

In [ ]:
b[[1,2], [1,2]]

array([5, 9])

Arithmetic operation in numpy array

In [ ]:
import numpy as np
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [ ]:
x+2


array([3, 4, 5, 6, 7])

In [ ]:
x**3

array([  1,   8,  27,  64, 125])

In [ ]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
x*2

array([2, 4, 6, 8])

In [ ]:
x-1

array([0, 1, 2, 3])

In [ ]:
x*3

array([ 3,  6,  9, 12])

In [ ]:
x**2

array([ 1,  4,  9, 16])

Numpy resize / reshape

In [ ]:
import numpy as np

a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.resize(a,(5,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 1]])

Flatten: Convert 2D, 3D array into 1D array

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.flatten()

array([1, 2, 3, 4])

In [ ]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Refer to `numpy.ndarray.transpose` for full documentation.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    ndarray.transpose : Equivalent method
    moveaxis
    argsort
    
    N

In [ ]:
array1 = np.arange(1,11).reshape(5,2)
array1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

Transpose in Numpy

In [ ]:
np.transpose(array1)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
array1.T

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

Split Function

In [ ]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [ ]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [ ]:
b = np.array([[1,2,3,4,5,8],[6,7,8,9,10,12]])
b

array([[ 1,  2,  3,  4,  5,  8],
       [ 6,  7,  8,  9, 10, 12]])

In [ ]:
np.vsplit(b,2)

[array([[1, 2, 3, 4, 5, 8]]), array([[ 6,  7,  8,  9, 10, 12]])]

In [ ]:
np.hsplit(b,2)

[array([[1, 2, 3],
        [6, 7, 8]]), array([[ 4,  5,  8],
        [ 9, 10, 12]])]

Insert Function()

In [3]:
a = np.arange(1,10)

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.insert(a,4,90)

array([ 1,  2,  3,  4, 90,  5,  6,  7,  8,  9])

In [ ]:
np.insert(a,(4,2),100)

array([  1,   2, 100,   3,   4, 100,   5,   6,   7,   8,   9])

Append()

In [6]:
np.append(a,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 25])

In [8]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [11]:
np.append(c,[[5],[6]],axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

Matrix in Numpy


In [13]:
a = np.array([[1,2],[3,4]])
b =np.array([[5,6],[7,8]])

In [16]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
b

array([[5, 6],
       [7, 8]])

Matrix

In [20]:
a = np.matrix("1 2;3 4")
a

matrix([[1, 2],
        [3, 4]])

In [ ]:
b = np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

Linear Algebra: inverse matrix

In [22]:
x = np.linalg.inv(b)
x

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

Solve Linear Equation in Numpy ( Numerical Python)

3x + y = 9

x + 2y = 8

x=2, y=3

In [23]:
import numpy as np
a = np.array([[3,1],[1,2]])

b = np.array([9,8])
b

array([9, 8])

In [24]:
a

array([[3, 1],
       [1, 2]])

In [25]:
x = np.linalg.solve(a,b)
x

array([2., 3.])

6x + 2y - 5z

3x + 3y - 2z

7x + 5y - 3z

x = 2 , y = 3, z = 1,

In [26]:
a = np.array([[6,2,-5],[3,3,-2],[7,5,-3]])
a

array([[ 6,  2, -5],
       [ 3,  3, -2],
       [ 7,  5, -3]])

In [ ]:
b = np.array([13,13,26])
b

array([13, 13, 26])

In [ ]:
x = np.linalg.solve(a,b)
x

array([2., 3., 1.])

Determinant in numpy

a = [[1,2], [3,4]]

a = -2

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
x = round(np.linalg.det(a))
x

-2

Another determinant:

a = [[1,2,3],[4,5,6],[7,8,9]]

a = 0

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.linalg.det(a)
x

0.0